In [10]:
import pandas
import numpy as np

In [7]:
print(type(1))
print(type(1.0))

<class 'int'>
<class 'float'>


In [8]:
"string"

'string'

In [9]:
'string'

'string'

In [13]:
print("My name is: {} my number is {}".format("Jose",10))
print("My name is: {x} my number is {y}".format(x="Jose",y=10))

My name is: Jose my number is 10
My name is: Jose my number is 10


In [26]:
myList = [1,2,3]
myList[1]
myList.append("d")
myList.append([1,2,3])
print(myList[4][2])

3


* arithmetic operators
* data structures
* logic operators
* control flow statements
    * decision making
        * if
        * switch
    * loops
        * do while
        * while
        * for, for each
    * jump statements
        * break
        * continue
* functions
* lambda expressions

## Python data structures
https://thomas-cokelaer.info/tutorials/python/data_structures.html

In [22]:
# lists lists=[1,2,3,4,5,"y"]
# tuples tuple=(2,4,"t")
# sets set={1,2,3,4}
# dictionary dict={"first":"string", "second":"this"}

In [25]:
tuple=(2,4,"t") # immutable
print(tuple[0])
dict={"first":"string", "second":"this"}
print(dict["first"])

2
string


In [27]:
1==2 and 2==2

False

In [28]:
1==2 or 2==2

True

In [33]:
if 1==1:
    print("oen is one")
elif 2==2:
    print("two is two")
else:
    print("math is fucked")

oen is one


In [34]:
seq=[1,2,3,4,5]
for item in seq:
    print(item)

1
2
3
4
5


In [36]:
i=1
while i<5:
    print("is is:{}".format(i))
    i=i+1

is is:1
is is:2
is is:3
is is:4


In [38]:
list(range(2,10,2))

[2, 4, 6, 8]

In [39]:
for i in range(5):
    print(i)

0
1
2
3
4


In [45]:
x=[1,2,3,4,5]
out=[]
for num in x:
    out.append(num**2)
print(out)

[1, 4, 9, 16, 25]


### List comprehension

In [43]:
[num**2 for num in x]

[1, 4, 9, 16, 25]

In [53]:
# shift+tab for function documentation
def func(x=4):
    '''
    This squares stuff
    '''
    return x**2
print(func(2))
print(func())
print(func(seq[0]))
arr = np.array([1,2,3,4])
print(func(arr))

4
16
1
[ 1  4  9 16]


In [54]:
def times_two(var):
    return var*2
times_two(4)

8

In [55]:
lambda var: var*2

<function __main__.<lambda>(var)>

In [60]:
st = "hello my name is Sam"
print(st.lower())
print(st.upper())
print(st.split("n")[-1])

hello my name is sam
HELLO MY NAME IS SAM
ame is Sam


In [62]:
d={'k1':'v1','k2':'v2'}
d.keys()
d.items()

dict_items([('k1', 'v1'), ('k2', 'v2')])

In [64]:
myList=[1,2,3]
last=myList.pop(-2)
print(myList)
'x' in myList

[1, 3]


False

## Indexing and selection
* grabbing single element
* grabbing a slice of elements
* broadcasting selections
* indexing and selection in 2-dimensions
* conditional selection

In [65]:
import numpy as np

In [66]:
arr=np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr[4]

4

In [70]:
arr[1:5:2]

array([1, 3])

In [72]:
arr[0:5]=100

In [73]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [74]:
arr=np.arange(0,11)

In [77]:
# just a reference of the original array
slice_of_arr=arr[0:5]
slice_of_arr[:]=99
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [78]:
arr_copy=arr.copy()

In [79]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [80]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [81]:
arr_2d.shape

(3, 3)

In [82]:
arr_2d[0] # first row

array([ 5, 10, 15])

In [90]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

## Conditional selection

In [85]:
arr=np.arange(1,11)
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [87]:
bool_arr = arr>4
print(bool_arr)

[False False False False  True  True  True  True  True  True]


In [88]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [89]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

## Numpy operations

In [91]:
import numpy as np

In [92]:
arr = np.arange(0,10)

In [93]:
arr + 5 # perform operation in an element by element basis

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [94]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [95]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [97]:
arr/arr # warning but no full error
# nan=not a number

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [98]:
np.sqrt(arr)
# np.sin
# np.log
# arr.sun()
# arr.mean()
# arr.max()
# arr.var()
# arr.std()

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [101]:
arr2d=np.arange(0,25).reshape(5,5)
print(arr2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [103]:
arr2d.sum(axis=0) # summing accross the rows

array([50, 55, 60, 65, 70])

In [104]:
arr2d.sum(axis=1) # accross columns

array([ 10,  35,  60,  85, 110])