In [1]:
# broadcasting abililty
# CREATING NUMPY ARRAYS

# transform standard python list
# built-in functions
# generating random data
import numpy as np

In [2]:
myList=[1,2,3]
type(myList)

list

In [3]:
myArray = np.array(myList)
type(myArray)

numpy.ndarray

In [5]:
my_matrix = [[1,2,3],[4,5,6]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.arange(0,10,1) # up to but not including
np.linspace(0,10,7) # including

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,5)) # rows, columns
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5,6)

array([[0.74345004, 0.28787839, 0.88524953, 0.50774452, 0.78813456,
        0.40173181],
       [0.22801037, 0.48030814, 0.4276885 , 0.94409529, 0.23904938,
        0.00952562],
       [0.31880518, 0.59846165, 0.74230613, 0.43293091, 0.55798435,
        0.04491088],
       [0.10944228, 0.26967324, 0.41721865, 0.21809018, 0.07078962,
        0.71982342],
       [0.25902739, 0.74796671, 0.55825786, 0.82017632, 0.22494072,
        0.72849498]])

In [17]:
# standard normal distribution
np.random.randn(10)

array([-0.11168687,  0.80038158,  0.70101277, -1.88522068, -0.84806463,
       -2.06609231, -0.17604184, -1.09119792,  1.44658101,  1.04731685])

In [20]:
np.random.randint(0,101,20)

array([ 5, 41, 94, 78, 56, 67, 52, 62, 86,  3, 86, 21, 72, 11, 47, 14, 32,
       30, 65, 99])

In [21]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [23]:
arr=np.arange(0,25)

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr=np.random.randint(0,101,10)

In [28]:
ranarr.max()

87

In [29]:
ranarr.argmin()

0

In [30]:
ranarr.dtype

dtype('int32')

In [32]:
arr.shape

(25,)

In [34]:
newarr=arr.reshape(5,5)
newarr.shape

(5, 5)